[package]
name = "glimmer-swc"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
swc_common = { path = "../swc/crates/swc_common", features=["tty-emitter"] }
swc = { path = "../swc/crates/swc" }
swc_core = { path = "../swc/crates/swc_core", features = ["ecma_plugin_transform"] }
swc_ecma_parser = { path = "../swc/crates/swc_ecma_parser" }
swc_ecma_codegen = { path = "../swc/crates/swc_ecma_codegen" }
swc_ecma_ast = { path = "../swc/crates/swc_ecma_ast" }
swc_ecma_visit = { path = "../swc/crates/swc_ecma_visit" }
swc_ecma_utils = { path = "../swc/crates/swc_ecma_utils" }
swc_ecma_transforms = { path = "../swc/crates/swc_ecma_transforms" }
lazy_static = "1.4.0"

wasm-bindgen = "0.2.63"

[dev-dependencies]
difference = "2"



