[package]
name = "glimmer-swc"
version = "0.1.0"
edition = "2021"

[dependencies]
swc_common = { path = "../swc/crates/swc_common", features=["tty-emitter"] }
swc_ecma_parser = { path = "../swc/crates/swc_ecma_parser" }


