[package]
name = "content-tag"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
swc_common = { path = "../swc/crates/swc_common", features=["tty-emitter"] }
swc = { path = "../swc/crates/swc" }
# The feature set here needs to be chosen carefully to not accidentally enable
# "plugin_mode" and the related stuff, because with that enabled, wasm32 builds
# expect swc plugin-runner specific environment that we don't use. When that
# happens, the javascript shims try to do "require('env')" to find the missing
# stuff, which is nonsense and blows up.
swc_core = { path = "../swc/crates/swc_core", features = ["ecma_ast", "common", "ecma_visit", "ecma_transforms", "__testing_transform"] }
swc_ecma_parser = { path = "../swc/crates/swc_ecma_parser" }
swc_ecma_codegen = { path = "../swc/crates/swc_ecma_codegen" }
swc_ecma_ast = { path = "../swc/crates/swc_ecma_ast" }
swc_ecma_visit = { path = "../swc/crates/swc_ecma_visit" }
swc_ecma_utils = { path = "../swc/crates/swc_ecma_utils" }
swc_ecma_transforms = { path = "../swc/crates/swc_ecma_transforms" }
lazy_static = "1.4.0"

wasm-bindgen = "0.2.63"

[dev-dependencies]
difference = "2"



